### ISSUE TITLE
Incompatible with gnome 41

### ISSUE THREAD

**Issue by CoderThomasB** [jeffchannell/jiggle#53]
The extension is listed as Incompatible with gnome 41.

**Comment by ismaail** [comment]
@CoderThomasB yes, but you can downloaded it and install it 

goto https://extensions.gnome.org/extension/3438/jiggle/ and follow this steps:

1. From the **Download** dropdown, choose **Shell Version 40.0** & **Extension Version 8**
2. extract the downloaded file
3. rename the extracted folder to: `jiggle@jeffchannell.com`
4. copy the folder to the extensions folder: `~/.local/share/gnome-shell/extensions`
5. open the file `metadata.json`, and add `41` to `shell-version` list
6. reload the Gnome-Shell or logout & login

**Comment by CoderThomasB** [comment]
I understand that this issue can be manually fixed by editing the metadata.json file locally but this issue relates to changing the metadata.json on GitHub and so defeating the need to do it manually.

**Comment by Guray00** [comment]
Is already updated, he only need to release the update...

**Comment by rohmishra** [comment]
Fixed in #51 
Build has not been released on Gnome Extensions.

You can disable version check on gnome to re-enable extension as extension is compatible with 41 with no changes.

**Comment by morfyum** [comment]
# +1 Incompatible with fresh Fedora 35 release :(
`Gnome 41.3` + `Wayland`
![image](https://user-images.githubusercontent.com/18602968/149632867-f7f8807d-4d6d-4488-a431-248d27f8a4eb.png)

**Comment by CoderThomasB** [comment]
It still appears as incomparable in the [https://extensions.gnome.org/extension/3438/jiggle/](https://extensions.gnome.org/extension/3438/jiggle/)

![2022-01-16_11-04](https://user-images.githubusercontent.com/47554072/149639103-c677d61c-bba9-40fd-a5bd-e6e064a70ab2.png)


![2022-01-16_11-03](https://user-images.githubusercontent.com/47554072/149639090-2ff77082-ca8a-4895-a336-7767ceaa542e.png)

**Comment by jeffchannell** [comment]
Versions updated here. New version coming in extensions very soon!

**Comment by jeffchannell** [comment]
https://extensions.gnome.org/review/32717

**Comment by yktoo** [comment]
It's been reject at the review AFAIS
